/**
 * Domain Schemas — Domain detection and implicit signal mappings.
 *
 * Dimensions (predefined question options) have been removed.
 * Questions are now generated by InvestigativeCommittee based on KG state.
 */

const DOMAIN_PATTERNS = {
  movie: {
    detect: (item) =>
      item.domain === 'movie' ||
      item.type === 'film' ||
      item.type === 'movie' ||
      (item.tags && item.tags.includes('film')) ||
      (item.metadata && (item.metadata.director || item.metadata.genre === 'movie')),
    implicitSignals: [
      { attribute: 'director', kgKey: 'director_style', kgType: 'belief' },
      { attribute: 'genre', kgKey: 'genre_preference', kgType: 'preference' },
      { attribute: 'genres', kgKey: 'genre_preference', kgType: 'preference' },
      { attribute: 'year', kgKey: 'film_era', kgType: 'preference' },
      { attribute: 'themes', kgKey: 'theme', kgType: 'identity' },
      { attribute: 'pacing', kgKey: 'pacing', kgType: 'preference' },
      { attribute: 'style', kgKey: 'director_style', kgType: 'belief' }
    ]
  },

  music: {
    detect: (item) =>
      item.domain === 'music' ||
      item.type === 'song' ||
      item.type === 'album' ||
      (item.tags && (item.tags.includes('music') || item.tags.includes('song'))),
    implicitSignals: [
      { attribute: 'artist', kgKey: 'artist_preference', kgType: 'belief' },
      { attribute: 'genre', kgKey: 'tempo', kgType: 'preference' },
      { attribute: 'tempo', kgKey: 'tempo', kgType: 'preference' },
      { attribute: 'lyrics', kgKey: 'lyrics', kgType: 'preference' },
      { attribute: 'production', kgKey: 'production', kgType: 'preference' }
    ]
  },

  article: {
    detect: (item) =>
      item.domain === 'article' ||
      item.type === 'article' ||
      item.type === 'blog' ||
      (item.tags && (item.tags.includes('article') || item.tags.includes('news'))),
    implicitSignals: [
      { attribute: 'topic', kgKey: 'topic_interest', kgType: 'belief' },
      { attribute: 'category', kgKey: 'topic_interest', kgType: 'belief' },
      { attribute: 'source', kgKey: 'reader_type', kgType: 'identity' },
      { attribute: 'style', kgKey: 'writing_style', kgType: 'preference' }
    ]
  },

  place: {
    detect: (item) =>
      item.domain === 'place' ||
      item.type === 'restaurant' ||
      item.type === 'venue' ||
      item.type === 'location' ||
      (item.title && /restaurant|cafe|bar|hotel|museum|park/i.test(item.title)),
    implicitSignals: [
      { attribute: 'cuisine', kgKey: 'cuisine', kgType: 'preference' },
      { attribute: 'atmosphere', kgKey: 'atmosphere', kgType: 'preference' },
      { attribute: 'price', kgKey: 'price_sensitivity', kgType: 'preference' },
      { attribute: 'price_range', kgKey: 'price_sensitivity', kgType: 'preference' }
    ]
  }
};

/**
 * Detect domain from an item.
 * @param {Object} item
 * @returns {string|null}
 */
export function detectDomain(item) {
  if (item.domain) return item.domain;
  for (const [domainName, schema] of Object.entries(DOMAIN_PATTERNS)) {
    if (schema.detect(item)) return domainName;
  }
  return null;
}

/**
 * Get schema for a domain.
 * @param {string} domain
 * @returns {Object|null}
 */
export function getDomainSchema(domain) {
  return DOMAIN_PATTERNS[domain] || null;
}

/**
 * Export DOMAINS as alias for entity-extractor compatibility.
 */
export const DOMAINS = DOMAIN_PATTERNS;
